# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestesy1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testesy1(self):
    self.driver.get("https://torrent-games.co/")
    self.driver.set_window_size(1380, 861)
    self.driver.find_element(By.LINK_TEXT, "Регистрация").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td:nth-child(2)").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("sadasfggd")
    self.driver.find_element(By.NAME, "password1").click()
    self.driver.find_element(By.NAME, "password1").send_keys("asffsafasg")
    self.driver.find_element(By.NAME, "password2").click()
    self.driver.find_element(By.NAME, "password2").send_keys("asgsafdasf")
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("saasfafa")
    self.driver.switch_to.frame(1)
    element = self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-checkmark")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "recaptcha-anchor").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".fbutton > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-button-text").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4)").click()
    self.driver.find_element(By.NAME, "password2").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3)").click()
    self.driver.find_element(By.NAME, "password1").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, ".fbutton > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".fbutton > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-button-text").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3)").click()
    self.driver.find_element(By.NAME, "password1").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4)").click()
    self.driver.find_element(By.NAME, "password2").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".fbutton > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) > .slides1 > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,200)")
  
